<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="LinkConsumerProvider" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://src/" xmlns:tns="LinkConsumerProvider" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://src/" location="http://PDLIL4.ip-37-187-166.eu:9080/LinkConsumerProvider-sun-http-binding/192.168.100.132_8080/Provider/ProvideWS.wsdl">
    </import>
  <portType name="dummyCasaPortType">
  </portType>
  <binding name="casaBinding1" type="ns:ProvideWS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="hello">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="sayYo">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="setProcessTime">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="processConsumerRequest">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="LinkConsumerProviderService1">
    <port name="casaPort1" binding="tns:casaBinding1">
      <soap:address location="http://PDLIL4.ip-37-187-166.eu:9080/LinkConsumerProviderService1/casaPort1"/>
    </port>
  </service>
</definitions>
